const base = import.meta.env.VITE_API_BASE_URL?.replace(/\/$/, '') || '/api/v1';
async function request<T>(path: string, options: RequestInit = {}): Promise<T> { const response = await fetch(`${base}${path}`, { ...options, credentials: 'include', headers: { ...(options.body === undefined ? {} : { 'Content-Type': 'application/json' }), ...options.headers } }); if (!response.ok) throw { status: response.status, ...(await response.json().catch(() => ({})) as object) }; return response.json() as Promise<T>; }
const query = (values: Record<string, string | number | undefined>) => new URLSearchParams(Object.entries(values).filter(([, value]) => value !== undefined && value !== '') as [string, string][]).toString();

export type ApiCashbox = { id: string; name: string; currency: 'USD' | 'SYP'; warehouseId: string | null; isDefault: boolean; isActive: boolean; openingBalance: number; inflowTotal: number; outflowTotal: number; balanceAmount: number; movementCount: number; notes: string; version: number };
export type ApiVoucher = { id: string; voucherNumber: string; type: 'receipt' | 'payment' | 'expense'; status: 'posted' | 'cancelled'; date: string; createdAt: string; sourceType: string; sourceDocumentNumber: string | null; sourceInvoiceId: string | null; sourceInvoiceNumber?: string | null; salesInvoiceId: string | null; purchaseInvoiceId: string | null; returnInvoiceId: string | null; partnerId: string | null; partnerName: string; cashBoxId: string; cashboxName: string; warehouseId: string | null; currency: 'USD' | 'SYP'; amount: number; exchangeRate: number; amountUSD: number; amountSYP: number; category: string; systemNote: string; userNote: string; statement: string; reversalOfVoucherId: string | null; cancelledAt: string | null; cancellationReason: string | null; createdBy: string; allocations?: Array<{ id: string; salesInvoiceId: string | null; purchaseInvoiceId: string | null; returnInvoiceId: string | null; amountUSD: number }> };
export type ApiCashMovement = { id: string; cashboxId: string; cashboxName: string; voucherId: string | null; voucherNumber: string; direction: 'inflow' | 'outflow'; amount: number; currency: 'USD' | 'SYP'; amountUSD: number; exchangeRate: number; partnerId: string | null; warehouseId: string | null; description: string; createdAt: string; actor: string };
export type ApiTransfer = { id: string; transferNumber: string; status: string; fromCashboxId: string; toCashboxId: string; amountFrom: number; amountTo: number; exchangeRate: number | null; note: string; createdAt: string; createdBy: string };
export type ApiStatementRow = { id: string; date: string; occurredAt: string; entryType: string; documentType: string; documentNumber: string; description: string; currency: 'USD' | 'SYP'; originalAmount: number; exchangeRate: number; debitUSD: number; creditUSD: number; runningBalanceUSD: number; salesInvoiceId: string | null; purchaseInvoiceId: string | null; returnInvoiceId: string | null; voucherId: string | null };
export type ApiStatement = { partner: { id: string; name: string; type: string; phone: string; openingBalanceUSD: number; openingGoldBalance21kGrams: number }; openingBalanceUSD: number; closingBalanceUSD: number; receivableUSD: number; payableUSD: number; rows: ApiStatementRow[] };
export type ApiPartnerBalance = { id: string; name: string; type: string; phone: string; netUSD: number; receivableUSD: number; payableUSD: number };
export type ApiFinanceSummary = { cashboxes: ApiCashbox[]; totalUsdCash: number; totalSypCash: number; totalReceivablesUSD: number; totalPayablesUSD: number };
export type VoucherInput = { type: 'receipt' | 'payment' | 'expense'; partnerId?: string; currency: 'USD' | 'SYP'; amount: string | number; exchangeRateSypPerUsd: string | number; cashBoxId?: string; warehouseId?: string; category?: string; userNote?: string; allocations?: Array<{ salesInvoiceId?: string; purchaseInvoiceId?: string; amountUSD: string | number }>; idempotencyKey: string };

export const financeApi = {
  summary: () => request<ApiFinanceSummary>('/finance/summary'),
  cashboxes: (filters: Record<string, string | undefined> = {}) => request<ApiCashbox[]>(`/finance/cashboxes?${query(filters)}`),
  createCashbox: (input: { name: string; currency: 'USD' | 'SYP'; warehouseId?: string; openingBalance?: string | number; isDefault?: boolean; notes?: string }) => request<ApiCashbox>('/finance/cashboxes', { method: 'POST', body: JSON.stringify(input) }),
  updateCashbox: (id: string, input: Record<string, unknown>) => request<ApiCashbox>(`/finance/cashboxes/${id}`, { method: 'PATCH', body: JSON.stringify(input) }),
  vouchers: (filters: Record<string, string | number | undefined> = {}) => request<{ items: ApiVoucher[]; meta: { page: number; limit: number; total: number } }>(`/finance/vouchers?${query(filters)}`),
  voucher: (id: string) => request<ApiVoucher>(`/finance/vouchers/${id}`),
  createVoucher: (input: VoucherInput) => request<ApiVoucher>('/finance/vouchers', { method: 'POST', body: JSON.stringify(input) }),
  cancelVoucher: (id: string, reason: string) => request<ApiVoucher>(`/finance/vouchers/${id}/cancel`, { method: 'POST', body: JSON.stringify({ reason }) }),
  transfers: (filters: Record<string, string | number | undefined> = {}) => request<{ items: ApiTransfer[]; meta: { page: number; limit: number; total: number } }>(`/finance/transfers?${query(filters)}`),
  createTransfer: (input: { fromCashboxId: string; toCashboxId: string; amountFrom: string | number; amountTo: string | number; exchangeRateSypPerUsd: string | number; note?: string; idempotencyKey: string }) => request<ApiTransfer>('/finance/transfers', { method: 'POST', body: JSON.stringify(input) }),
  movements: (filters: Record<string, string | number | undefined> = {}) => request<{ items: ApiCashMovement[]; meta: { page: number; limit: number; total: number } }>(`/finance/movements?${query(filters)}`),
  partnerBalances: (filters: Record<string, string | number | undefined> = {}) => request<ApiPartnerBalance[]>(`/finance/partner-balances?${query(filters)}`),
  partnerStatement: (partnerId: string, filters: Record<string, string | undefined> = {}) => request<ApiStatement>(`/finance/partners/${partnerId}/statement?${query(filters)}`),
  expenseCategories: () => request<Array<{ id: string; name: string }>>('/finance/expense-categories'),
  createExpenseCategory: (name: string) => request<{ id: string; name: string }>('/finance/expense-categories', { method: 'POST', body: JSON.stringify({ name }) }),
};
