import type { InventoryItem, Warehouse } from '../types';
const base = import.meta.env.VITE_API_BASE_URL?.replace(/\/$/, '') || '/api/v1';
async function request<T>(path: string, options: RequestInit = {}): Promise<T> { const response = await fetch(`${base}${path}`, { ...options, credentials: 'include', headers: { ...(options.body === undefined || options.body instanceof Blob ? {} : { 'Content-Type': 'application/json' }), ...options.headers } }); if (!response.ok) throw { status: response.status, ...(await response.json().catch(() => ({})) as object) }; return response.json() as Promise<T>; }
export type ApiInventoryItem = InventoryItem & { version: number; imagePath?: string; archivedAt?: string | null };
export const inventoryApi = {
  list: (query: Record<string, string | number | undefined>) => request<{ items: ApiInventoryItem[]; meta: { page: number; limit: number; total: number } }>(`/inventory?${new URLSearchParams(Object.entries(query).filter(([, value]) => value !== undefined && value !== '') as [string, string][]).toString()}`),
  create: (input: Record<string, unknown>) => request<ApiInventoryItem>('/inventory', { method: 'POST', body: JSON.stringify(input) }), update: (id: string, input: Record<string, unknown>) => request<ApiInventoryItem>(`/inventory/${id}`, { method: 'PATCH', body: JSON.stringify(input) }), archive: (id: string, version: number) => request(`/inventory/${id}`, { method: 'DELETE', body: JSON.stringify({ version }) }), transfer: (id: string, input: Record<string, unknown>) => request<ApiInventoryItem>(`/inventory/${id}/transfer`, { method: 'POST', body: JSON.stringify(input) }),
  warehouses: () => request<Warehouse[]>('/warehouses'), createWarehouse: (input: Record<string, unknown>) => request<Warehouse>('/warehouses', { method: 'POST', body: JSON.stringify(input) }), updateWarehouse: (id: string, input: Record<string, unknown>) => request<Warehouse>(`/warehouses/${id}`, { method: 'PATCH', body: JSON.stringify(input) }), deleteWarehouse: (id: string) => request(`/warehouses/${id}`, { method: 'DELETE' }), stocktake: (warehouseId: string) => request(`/inventory/stocktakes/${warehouseId}`, { method: 'POST' }), uploadImage: (blob: Blob) => request<{ imagePath: string; imageUrl: string }>('/inventory/images', { method: 'POST', body: blob, headers: { 'Content-Type': blob.type || 'image/jpeg' } }),
};
