ALTER TABLE "roles" ADD COLUMN IF NOT EXISTS "is_system" boolean DEFAULT false NOT NULL;
--> statement-breakpoint
INSERT INTO "permissions" ("code", "description") VALUES ('inventory.view', 'inventory.view'), ('inventory.create', 'inventory.create'), ('inventory.update', 'inventory.update'), ('inventory.delete', 'inventory.delete'), ('inventory.transfer', 'inventory.transfer'), ('inventory.adjust', 'inventory.adjust'), ('sales.view', 'sales.view'), ('sales.create', 'sales.create'), ('sales.update', 'sales.update'), ('sales.cancel', 'sales.cancel'), ('sales.return', 'sales.return'), ('sales.discount', 'sales.discount'), ('sales.approve', 'sales.approve'), ('purchases.view', 'purchases.view'), ('purchases.create', 'purchases.create'), ('purchases.cancel', 'purchases.cancel'), ('returns.view', 'returns.view'), ('returns.create', 'returns.create'), ('returns.cancel', 'returns.cancel'), ('customers.view', 'customers.view'), ('customers.create', 'customers.create'), ('customers.update', 'customers.update'), ('customers.archive', 'customers.archive'), ('suppliers.view', 'suppliers.view'), ('suppliers.create', 'suppliers.create'), ('suppliers.update', 'suppliers.update'), ('suppliers.archive', 'suppliers.archive'), ('reports.view', 'reports.view'), ('users.view', 'users.view'), ('users.manage', 'users.manage'), ('warehouses.view', 'warehouses.view'), ('warehouses.manage', 'warehouses.manage'), ('warehouses.scope.all', 'warehouses.scope.all'), ('finance.view', 'finance.view'), ('finance.cashbox.manage', 'finance.cashbox.manage'), ('finance.voucher.create', 'finance.voucher.create'), ('finance.voucher.cancel', 'finance.voucher.cancel'), ('finance.transfer', 'finance.transfer'), ('accounting.view', 'accounting.view'), ('accounting.accounts.manage', 'accounting.accounts.manage'), ('accounting.journal.create', 'accounting.journal.create'), ('accounting.journal.reverse', 'accounting.journal.reverse'), ('gold_accounts.view', 'gold_accounts.view'), ('gold_accounts.transaction.create', 'gold_accounts.transaction.create'), ('gold_accounts.adjust', 'gold_accounts.adjust'), ('gold_accounts.convert', 'gold_accounts.convert'), ('gold_accounts.reverse', 'gold_accounts.reverse'), ('data.scope.own', 'data.scope.own') ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO "role_permissions" ("role_id", "permission_id") SELECT "roles"."id", "permissions"."id" FROM "roles" CROSS JOIN "permissions" WHERE "roles"."name" = 'system_admin' AND "permissions"."code" <> 'data.scope.own' ON CONFLICT DO NOTHING;
--> statement-breakpoint
UPDATE "roles" SET "is_system" = true WHERE "name" = 'system_admin';
--> statement-breakpoint
UPDATE "roles" SET "is_system" = true WHERE "name" LIKE 'override:%';
--> statement-breakpoint
INSERT INTO "roles" ("name", "display_name", "description", "is_system") VALUES ('general_manager', 'المدير العام', 'صلاحية كاملة على كل فروع الشركة الحالية والمستقبلية دون ربط بمستودع.', false) ON CONFLICT ("name") DO UPDATE SET "display_name" = EXCLUDED."display_name", "description" = EXCLUDED."description", "is_system" = false, "is_active" = true;
--> statement-breakpoint
DELETE FROM "role_permissions" WHERE "role_id" IN (SELECT "id" FROM "roles" WHERE "name" = 'general_manager');
--> statement-breakpoint
INSERT INTO "role_permissions" ("role_id", "permission_id") SELECT "roles"."id", "permissions"."id" FROM "roles" CROSS JOIN "permissions" WHERE "roles"."name" = 'general_manager' AND "permissions"."code" IN ('inventory.view', 'inventory.create', 'inventory.update', 'inventory.delete', 'inventory.transfer', 'inventory.adjust', 'sales.view', 'sales.create', 'sales.update', 'sales.cancel', 'sales.return', 'sales.discount', 'sales.approve', 'purchases.view', 'purchases.create', 'purchases.cancel', 'returns.view', 'returns.create', 'returns.cancel', 'customers.view', 'customers.create', 'customers.update', 'customers.archive', 'suppliers.view', 'suppliers.create', 'suppliers.update', 'suppliers.archive', 'reports.view', 'users.view', 'users.manage', 'warehouses.view', 'warehouses.manage', 'warehouses.scope.all', 'finance.view', 'finance.cashbox.manage', 'finance.voucher.create', 'finance.voucher.cancel', 'finance.transfer', 'accounting.view', 'accounting.accounts.manage', 'accounting.journal.create', 'accounting.journal.reverse', 'gold_accounts.view', 'gold_accounts.transaction.create', 'gold_accounts.adjust', 'gold_accounts.convert', 'gold_accounts.reverse') ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO "roles" ("name", "display_name", "description", "is_system") VALUES ('warehouse_manager', 'مدير مستودع', 'إدارة كاملة لحركة المستودعات المسندة إليه ومتابعة عمل البائعين داخلها.', false) ON CONFLICT ("name") DO UPDATE SET "display_name" = EXCLUDED."display_name", "description" = EXCLUDED."description", "is_system" = false, "is_active" = true;
--> statement-breakpoint
DELETE FROM "role_permissions" WHERE "role_id" IN (SELECT "id" FROM "roles" WHERE "name" = 'warehouse_manager');
--> statement-breakpoint
INSERT INTO "role_permissions" ("role_id", "permission_id") SELECT "roles"."id", "permissions"."id" FROM "roles" CROSS JOIN "permissions" WHERE "roles"."name" = 'warehouse_manager' AND "permissions"."code" IN ('inventory.view', 'inventory.create', 'inventory.update', 'inventory.transfer', 'inventory.adjust', 'sales.view', 'sales.create', 'sales.update', 'sales.cancel', 'sales.return', 'sales.discount', 'purchases.view', 'purchases.create', 'purchases.cancel', 'returns.view', 'returns.create', 'returns.cancel', 'customers.view', 'customers.create', 'customers.update', 'suppliers.view', 'suppliers.create', 'suppliers.update', 'reports.view', 'users.view', 'users.manage', 'warehouses.view', 'finance.view', 'finance.voucher.create', 'accounting.view', 'gold_accounts.view', 'gold_accounts.transaction.create') ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO "roles" ("name", "display_name", "description", "is_system") VALUES ('sales', 'بائع', 'قسم الفواتير فقط داخل مستودع واحد، ولا يرى إلا فواتيره هو.', false) ON CONFLICT ("name") DO UPDATE SET "display_name" = EXCLUDED."display_name", "description" = EXCLUDED."description", "is_system" = false, "is_active" = true;
--> statement-breakpoint
DELETE FROM "role_permissions" WHERE "role_id" IN (SELECT "id" FROM "roles" WHERE "name" = 'sales');
--> statement-breakpoint
INSERT INTO "role_permissions" ("role_id", "permission_id") SELECT "roles"."id", "permissions"."id" FROM "roles" CROSS JOIN "permissions" WHERE "roles"."name" = 'sales' AND "permissions"."code" IN ('sales.view', 'sales.create', 'returns.view', 'returns.create', 'customers.view', 'customers.create', 'warehouses.view', 'data.scope.own') ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO "user_roles" ("user_id", "role_id") SELECT "user_roles"."user_id", "target"."id" FROM "user_roles" INNER JOIN "roles" AS "source" ON "source"."id" = "user_roles"."role_id" CROSS JOIN "roles" AS "target" WHERE "source"."name" = 'system_admin' AND "target"."name" = 'general_manager' ON CONFLICT DO NOTHING;
