import { Body, ConflictException, Controller, Delete, Get, Inject, Param, Patch, Post, Req, UseGuards } from '@nestjs/common';
import type { FastifyRequest } from 'fastify';
import { eq, inArray, or, sql } from 'drizzle-orm';
import { DATABASE, type Database } from '../database/database.module.js';
import { inventoryItems, inventoryMovements, purchaseInvoices, salesInvoices, stocktakes, userWarehouses, warehouses } from '../database/schema.js';
import { AuthGuard } from '../auth/auth.guard.js';
import { PermissionGuard } from '../permissions/permission.guard.js';
import { RequirePermissions } from '../permissions/require-permissions.decorator.js';
import { WarehouseScopeService } from './warehouse-scope.service.js';
import { ensureWarehouseDefaultCashboxes } from '../finance/warehouse-default-cashboxes.js';

@Controller('warehouses') @UseGuards(AuthGuard, PermissionGuard)
export class WarehousesController {
  constructor(@Inject(WarehouseScopeService) private readonly scope: WarehouseScopeService, @Inject(DATABASE) private readonly db: Database) {}
  @Get() @RequirePermissions('warehouses.view')
  async list(@Req() request: FastifyRequest) { const user = request.identity!; const rows = await this.db.select().from(warehouses).where(this.scope.canAccessAll(user) ? undefined : inArray(warehouses.id, this.scope.allowedWarehouseIds(user) ?? [])); return rows; }
  @Post() @RequirePermissions('warehouses.manage')
  async create(@Req() request: FastifyRequest, @Body() body: Record<string, unknown>) { const name = typeof body.name === 'string' ? body.name.trim() : ''; if (!name || name.length > 160) throw new ConflictException('Warehouse name is invalid.'); const location = typeof body.location === 'string' ? body.location.trim().slice(0, 250) : null; const duplicate = await this.findDuplicate(name, location); if (duplicate) throw new ConflictException('A warehouse with the same name and location already exists.'); const managerUserId = typeof body.managerUserId === 'string' && body.managerUserId ? body.managerUserId : null; return this.db.transaction(async tx => { const created = (await tx.insert(warehouses).values({ name, location, phone: typeof body.phone === 'string' ? body.phone.trim().slice(0, 50) : null, managerUserId }).returning())[0]!; if (managerUserId) await tx.insert(userWarehouses).values({ userId: managerUserId, warehouseId: created.id, isManager: true }).onConflictDoNothing(); await ensureWarehouseDefaultCashboxes(tx, created.id, request.identity!.id); return created; }); }
  @Patch(':warehouseId') @RequirePermissions('warehouses.manage')
  async update(@Req() request: FastifyRequest, @Param('warehouseId') warehouseId: string, @Body() body: Record<string, unknown>) { this.scope.assertAccess(request.identity!, warehouseId); const values = { name: typeof body.name === 'string' ? body.name.trim().slice(0, 160) : undefined, location: typeof body.location === 'string' ? body.location.trim().slice(0, 250) : undefined, phone: typeof body.phone === 'string' ? body.phone.trim().slice(0, 50) : undefined, isActive: typeof body.isActive === 'boolean' ? body.isActive : undefined, managerUserId: typeof body.managerUserId === 'string' ? body.managerUserId || null : undefined, updatedAt: new Date() }; const row = (await this.db.update(warehouses).set(values).where(eq(warehouses.id, warehouseId)).returning())[0]; if (!row) throw new ConflictException('Warehouse not found.'); if (row.managerUserId) await this.db.insert(userWarehouses).values({ userId: row.managerUserId, warehouseId: row.id, isManager: true }).onConflictDoNothing(); return row; }
  @Delete(':warehouseId') @RequirePermissions('warehouses.manage')
  async remove(@Req() request: FastifyRequest, @Param('warehouseId') warehouseId: string) { this.scope.assertAccess(request.identity!, warehouseId); const [items, movements, sales, purchases, snapshots, assignments] = await Promise.all([this.db.select({ id: inventoryItems.id }).from(inventoryItems).where(eq(inventoryItems.warehouseId, warehouseId)).limit(1), this.db.select({ id: inventoryMovements.id }).from(inventoryMovements).where(or(eq(inventoryMovements.fromWarehouseId, warehouseId), eq(inventoryMovements.toWarehouseId, warehouseId))).limit(1), this.db.select({ id: salesInvoices.id }).from(salesInvoices).where(eq(salesInvoices.warehouseId, warehouseId)).limit(1), this.db.select({ id: purchaseInvoices.id }).from(purchaseInvoices).where(eq(purchaseInvoices.warehouseId, warehouseId)).limit(1), this.db.select({ id: stocktakes.id }).from(stocktakes).where(eq(stocktakes.warehouseId, warehouseId)).limit(1), this.db.select({ userId: userWarehouses.userId }).from(userWarehouses).where(eq(userWarehouses.warehouseId, warehouseId)).limit(1)]); if (items.length || movements.length || sales.length || purchases.length || snapshots.length || assignments.length) throw new ConflictException('A warehouse with inventory, movements, invoices, snapshots, or user assignments cannot be deleted.'); const row = (await this.db.delete(warehouses).where(eq(warehouses.id, warehouseId)).returning())[0]; if (!row) throw new ConflictException('Warehouse not found.'); return { id: row.id, deleted: true }; }
  @Get('scope') @RequirePermissions('warehouses.view')
  scopeForCurrentUser(@Req() request: FastifyRequest) { const user = request.identity!; return { allWarehouses: this.scope.canAccessAll(user), warehouses: user.warehouses }; }
  @Get(':warehouseId/access') @RequirePermissions('warehouses.view')
  checkAccess(@Req() request: FastifyRequest, @Param('warehouseId') warehouseId: string) { this.scope.assertAccess(request.identity!, warehouseId); return { warehouseId, allowed: true }; }
  private async findDuplicate(name: string, location: string | null) { const rows = await this.db.select({ id: warehouses.id }).from(warehouses).where(sql`lower(btrim(${warehouses.name})) = lower(btrim(${name})) and coalesce(lower(btrim(${warehouses.location})), '') = coalesce(lower(btrim(${location ?? ''})), '')`).limit(1); return rows[0]; }
}
