import React, { useEffect, useMemo, useState } from 'react';
import { CalendarDays, FileDown, MessageCircle, Printer, Search, X } from 'lucide-react';
import type { ApiPartner } from '../services/partnersApi';
import { goldApi, type ApiGoldStatementRow } from '../services/goldApi';
import { useStore } from '../context/StoreContext';

export const CustomerGoldStatementModal: React.FC<{ partner: ApiPartner; onClose: () => void }> = ({ partner, onClose }) => {
  const { settings } = useStore();
  const [from, setFrom] = useState(''); const [to, setTo] = useState(''); const [query, setQuery] = useState('');
  const [rows, setRows] = useState<ApiGoldStatementRow[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = async () => { setLoading(true); try { const statement = await goldApi.statement(partner.id, { dateFrom: from || undefined, dateTo: to || undefined }); setRows(statement.rows); setError(''); } catch (reason: any) { setError(reason?.message || 'تعذر تحميل كشف الأوزان.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [partner.id, from, to]);
  useEffect(() => { document.body.classList.add('customer-statement-print-active'); return () => document.body.classList.remove('customer-statement-print-active'); }, []);
  const shown = useMemo(() => rows.filter(row => !query.trim() || `${row.description} ${row.transactionNumber} ${row.karat}`.toLowerCase().includes(query.trim().toLowerCase())), [rows, query]);
  const totals = useMemo(() => Object.values(shown.reduce<Record<string, { karat: string; ours: number; theirs: number; balance: number }>>((all, row) => { const current = all[row.karat] ?? { karat: row.karat, ours: 0, theirs: 0, balance: 0 }; current.ours += row.debitGrams; current.theirs += row.creditGrams; current.balance = row.runningBalanceGrams; all[row.karat] = current; return all; }, {})).sort((a, b) => Number(b.karat) - Number(a.karat)), [shown]);
  const share = () => { const text = `${settings.storeName}\nكشف حساب أوزان العميل: ${partner.name}\n${from || 'البداية'} — ${to || 'اليوم'}\n${totals.map(row => `عيار ${row.karat}: لنا ${row.ours.toFixed(3)}غ | له ${row.theirs.toFixed(3)}غ | الرصيد ${row.balance.toFixed(3)}غ`).join('\n')}\nعدد العمليات: ${shown.length}`; window.open(`https://wa.me/?text=${encodeURIComponent(text)}`, '_blank', 'noopener,noreferrer'); };
  return <div className="fixed inset-0 z-[120] bg-slate-950/70 p-2 backdrop-blur-sm sm:p-5" dir="rtl"><div className="customer-statement-sheet mx-auto flex h-full max-w-5xl flex-col overflow-hidden rounded-sm bg-white shadow-2xl">
    <header className="no-print flex items-center justify-between gap-2 border-b border-slate-200 p-3"><div><h2 className="text-base font-black text-slate-900">كشف حساب العميل — الأوزان</h2><p className="text-[11px] font-bold text-slate-500">{partner.name}</p></div><div className="flex gap-1"><button onClick={() => window.print()} className="rounded-sm bg-amber-400 p-2 text-slate-900"><Printer className="h-4 w-4" /></button><button onClick={share} className="rounded-sm bg-emerald-600 p-2 text-white"><MessageCircle className="h-4 w-4" /></button><button onClick={onClose} className="rounded-sm bg-slate-100 p-2"><X className="h-4 w-4" /></button></div></header>
    <section className="customer-statement-paper flex-1 overflow-auto p-3 sm:p-5"><div className="flex items-start justify-between border-b-2 border-amber-400 pb-3"><div><h1 className="text-lg font-black text-slate-900">{settings.storeName}</h1><p className="text-xs text-slate-500">كشف حساب أوزان ذهب</p></div><div className="text-left text-[11px] font-bold text-slate-600">العميل: {partner.name}<br />تاريخ الطباعة: {new Date().toLocaleDateString('ar-SY')}</div></div>
      <div className="no-print mt-3 grid gap-2 sm:grid-cols-4"><label className="text-xs font-bold">من<input type="date" value={from} onChange={e => setFrom(e.target.value)} className="mt-1 w-full border p-2" /></label><label className="text-xs font-bold">إلى<input type="date" value={to} onChange={e => setTo(e.target.value)} className="mt-1 w-full border p-2" /></label><label className="relative sm:col-span-2"><Search className="absolute right-2 top-8 h-4 w-4 text-slate-400" /><span className="text-xs font-bold">بحث في الحركات</span><input value={query} onChange={e => setQuery(e.target.value)} className="mt-1 w-full border py-2 pr-8" placeholder="البيان أو رقم الحركة أو العيار" /></label></div>
      {loading ? <p className="p-8 text-center text-sm text-slate-500">جارٍ تحميل الحركات…</p> : error ? <p className="p-5 text-rose-700">{error}</p> : <><div className="mt-4 overflow-x-auto"><table className="w-full border-collapse text-right text-[11px]"><thead className="bg-slate-900 text-amber-400"><tr><th className="p-2">التاريخ</th><th className="p-2">التفاصيل</th><th className="p-2">لنا</th><th className="p-2">له</th><th className="p-2">الرصيد</th></tr></thead><tbody>{shown.map(row => <tr key={row.id} className={row.status === 'reversed' ? 'bg-slate-100 text-slate-400 line-through' : 'border-b'}><td className="p-2 font-mono">{row.date}</td><td className="p-2"><b>{row.description}</b><small className="mr-1 text-slate-500">{row.transactionNumber} · عيار {row.karat}</small></td><td className="p-2 font-mono text-amber-800">{row.debitGrams ? `${row.debitGrams.toFixed(3)} غ` : '—'}</td><td className="p-2 font-mono text-rose-700">{row.creditGrams ? `${row.creditGrams.toFixed(3)} غ` : '—'}</td><td className="p-2 font-mono font-black">{row.runningBalanceGrams.toFixed(3)} غ</td></tr>)}{!shown.length && <tr><td colSpan={5} className="p-8 text-center text-slate-500">لا توجد حركات ضمن الفترة المختارة.</td></tr>}</tbody></table></div><footer className="mt-4 border-t-2 border-amber-400 pt-3"><p className="text-xs font-black text-slate-700">إجمالي العمليات: {shown.length}</p><div className="mt-2 grid gap-2 sm:grid-cols-3">{totals.map(row => <div key={row.karat} className="border-r-4 border-amber-400 bg-amber-50 p-2 text-xs"><b>عيار {row.karat}</b><p>لنا: {row.ours.toFixed(3)} غ · له: {row.theirs.toFixed(3)} غ</p><p className="font-black">الرصيد: {row.balance.toFixed(3)} غ</p></div>)}</div></footer></>}</section>
    <footer className="no-print flex justify-end gap-2 border-t p-3"><button onClick={() => window.print()} className="flex items-center gap-1 rounded-sm bg-slate-900 px-3 py-2 text-xs font-bold text-amber-400"><FileDown className="h-4 w-4" />طباعة / PDF A5</button></footer>
  </div></div>;
};
