import React, { useEffect, useState } from 'react';
import { Archive, Banknote, Camera, EllipsisVertical, Pencil, Plus, Printer, Search, UserRound, WalletCards, X } from 'lucide-react';
import { employeesApi, type Employee } from '../services/employeesApi';
import { inventoryApi } from '../services/inventoryApi';
import type { Warehouse } from '../types';

const labels = { daily:'يومي', weekly:'أسبوعي', monthly:'شهري' };
const empty = { fullName:'', phone:'', warehouseId:'', schedule:'monthly', salaryCurrency:'USD', salaryAmount:'', notes:'', photoDataUrl:'' };
export const EmployeesView: React.FC = () => {
  const [employees,setEmployees]=useState<Employee[]>([]), [warehouses,setWarehouses]=useState<Warehouse[]>([]), [search,setSearch]=useState(''), [error,setError]=useState(''), [editing,setEditing]=useState<Employee|null>(null), [formOpen,setFormOpen]=useState(false), [details,setDetails]=useState<Employee|null>(null), [menu,setMenu]=useState<string|null>(null);
  const load=async()=>{ try { const [list,wh]=await Promise.all([employeesApi.list(search),inventoryApi.warehouses()]); setEmployees(list);setWarehouses(wh); } catch(e:any){setError(e.message||'تعذر تحميل الموظفين.');} };
  useEffect(()=>{void load();},[]); useEffect(()=>{const id=setTimeout(()=>void load(),250);return()=>clearTimeout(id);},[search]);
  const open=(employee?:Employee)=>{setEditing(employee??null);setFormOpen(true);setMenu(null);};
  const detail=async(id:string)=>{try{setDetails(await employeesApi.get(id));setMenu(null);}catch(e:any){setError(e.message||'تعذر تحميل بيانات الموظف.');}};
  const print=async(id:string)=>{await detail(id);setTimeout(()=>window.print(),100);};
  return <div className="space-y-4">
    <header className="flex flex-col gap-3 rounded-sm border-2 border-slate-200 bg-white p-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-2"><span className="grid h-10 w-10 place-items-center bg-slate-900 text-amber-400"><UserRound className="h-5 w-5"/></span><div><h2 className="font-black text-slate-900">الموظفين</h2><p className="text-[11px] font-bold text-slate-500">المستودع والدوام والراتب والسلف</p></div></div><button onClick={()=>open()} className="flex items-center justify-center gap-2 bg-amber-400 px-4 py-2.5 text-xs font-black text-slate-900"><Plus className="h-4 w-4"/>موظف جديد</button></header>
    <div className="relative"><Search className="absolute right-3 top-3 h-4 w-4 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="ابحث باسم الموظف" className="h-10 w-full border-2 border-slate-200 bg-white pr-9 px-3 text-sm font-bold outline-none focus:border-amber-400"/></div>{error&&<p className="border border-rose-200 bg-rose-50 p-3 text-xs font-bold text-rose-700">{error}</p>}
    <div className="overflow-hidden border-2 border-slate-200 bg-white"><table className="w-full text-right text-xs"><thead className="bg-slate-900 text-amber-400"><tr><th className="p-3">الموظف</th><th className="p-3">المستودع</th><th className="p-3">الدوام والراتب</th><th className="p-3">السلف</th><th className="p-3"></th></tr></thead><tbody>{employees.map(e=>{const t=e.totals[e.salaryCurrency]||{advances:0,salaryPayments:0};return <tr key={e.id} className="border-t border-slate-100"><td className="p-3"><div className="flex items-center gap-2"><img src={e.photoDataUrl||'/logo-transparent.png'} className="h-9 w-9 rounded-full object-cover"/><b>{e.fullName}</b></div></td><td className="p-3 font-bold text-slate-600">{e.warehouseName}</td><td className="p-3"><b>{labels[e.schedule]}</b><br/><span>{e.salaryAmount.toLocaleString()} {e.salaryCurrency==='USD'?'$':'ل.س'}</span></td><td className="p-3 font-bold text-rose-700">{t.advances.toLocaleString()} {e.salaryCurrency==='USD'?'$':'ل.س'}</td><td className="relative p-3"><button onClick={()=>setMenu(menu===e.id?null:e.id)}><EllipsisVertical className="h-5 w-5"/></button>{menu===e.id&&<div className="absolute left-2 z-20 w-36 border bg-white shadow-lg"><button onClick={()=>detail(e.id)} className="block w-full p-2 text-right">بيانات الموظف</button><button onClick={()=>open(e)} className="block w-full p-2 text-right">تعديل</button><button onClick={()=>print(e.id)} className="block w-full p-2 text-right">طباعة / PDF</button><button onClick={()=>void employeesApi.archive(e.id).then(load)} className="block w-full p-2 text-right text-amber-700">أرشفة</button><button onClick={()=>void employeesApi.terminate(e.id).then(load)} className="block w-full p-2 text-right text-rose-700">إنهاء خدمة</button></div>}</td></tr>})}{!employees.length&&<tr><td colSpan={5} className="p-10 text-center font-bold text-slate-400">لا يوجد موظفون.</td></tr>}</tbody></table></div>
    {formOpen&&<EmployeeForm employee={editing} warehouses={warehouses} onClose={()=>setFormOpen(false)} onSaved={()=>{setFormOpen(false);void load();}}/>}{details&&<EmployeeDetail employee={details} onClose={()=>setDetails(null)} onSaved={()=>{setDetails(null);void load();}}/>}
  </div>;
};
const EmployeeForm=({employee,warehouses,onClose,onSaved}:{employee:Employee|null;warehouses:Warehouse[];onClose:()=>void;onSaved:()=>void})=>{const [f,setF]=useState<any>(employee?{...employee,salaryAmount:String(employee.salaryAmount),photoDataUrl:employee.photoDataUrl||''}:empty),[error,setError]=useState('');const set=(k:string,v:any)=>setF({...f,[k]:v});const photo=(file?:File)=>{if(!file)return;const r=new FileReader();r.onload=()=>set('photoDataUrl',String(r.result));r.readAsDataURL(file)};const save=async()=>{try{if(employee)await employeesApi.update(employee.id,f);else await employeesApi.create(f);onSaved()}catch(e:any){setError(e.message||'تعذر الحفظ.')}};return <Modal title={employee?'تعديل موظف':'موظف جديد'} close={onClose}><div className="grid gap-3"><label>الاسم<input value={f.fullName} onChange={e=>set('fullName',e.target.value)} className="field"/></label><label>الهاتف<input value={f.phone||''} onChange={e=>set('phone',e.target.value)} className="field"/></label><label>المستودع<select value={f.warehouseId} onChange={e=>set('warehouseId',e.target.value)} className="field"><option value="">اختر المستودع</option>{warehouses.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label><div className="grid grid-cols-2 gap-2"><label>الدوام<select value={f.schedule} onChange={e=>set('schedule',e.target.value)} className="field"><option value="daily">يومي</option><option value="weekly">أسبوعي</option><option value="monthly">شهري</option></select></label><label>العملة<select value={f.salaryCurrency} onChange={e=>set('salaryCurrency',e.target.value)} className="field"><option value="USD">دولار</option><option value="SYP">ليرة سورية</option></select></label></div><label>الراتب<input type="number" value={f.salaryAmount} onChange={e=>set('salaryAmount',e.target.value)} className="field"/></label><label className="flex items-center gap-2 border p-2 text-xs font-bold"><Camera className="h-4 w-4"/>رفع أو التقاط صورة<input type="file" accept="image/*" capture="user" onChange={e=>photo(e.target.files?.[0])}/></label><label>ملاحظات<textarea value={f.notes||''} onChange={e=>set('notes',e.target.value)} className="field min-h-20"/></label>{error&&<p className="text-xs font-bold text-rose-600">{error}</p>}<button onClick={()=>void save()} className="bg-amber-400 p-3 text-xs font-black">حفظ</button></div></Modal>};
const EmployeeDetail=({employee,onClose,onSaved}:{employee:Employee;onClose:()=>void;onSaved:()=>void})=>{const [type,setType]=useState<'advance'|'salary_payment'>('advance'),[amount,setAmount]=useState(''),[note,setNote]=useState(''),[error,setError]=useState('');const pay=async()=>{try{await employeesApi.transaction(employee.id,{type,amount,currency:employee.salaryCurrency,note,idempotencyKey:crypto.randomUUID()});onSaved()}catch(e:any){setError(e.message||'تعذر تسجيل الحركة.')}};const t=employee.totals[employee.salaryCurrency]||{advances:0,salaryPayments:0};return <Modal title={employee.fullName} close={onClose}><div className="employee-print space-y-3"><div className="flex items-center gap-3"><img src={employee.photoDataUrl||'/logo-transparent.png'} className="h-14 w-14 rounded-full object-cover"/><div><b>{employee.warehouseName}</b><p>{labels[employee.schedule]} — {employee.salaryAmount} {employee.salaryCurrency}</p></div></div><div className="grid grid-cols-2 gap-2"><b className="bg-rose-50 p-3">السلف: {t.advances}</b><b className="bg-emerald-50 p-3">رواتب مسلمة: {t.salaryPayments}</b></div><div className="border-t pt-3"><select value={type} onChange={e=>setType(e.target.value as any)} className="field"><option value="advance">سلفة</option><option value="salary_payment">تسليم راتب</option></select><input type="number" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="المبلغ" className="field mt-2"/><input value={note} onChange={e=>setNote(e.target.value)} placeholder="ملاحظة" className="field mt-2"/><button onClick={()=>void pay()} className="mt-2 flex w-full items-center justify-center gap-2 bg-slate-900 p-3 text-xs font-black text-amber-400"><WalletCards className="h-4 w-4"/>تسجيل الحركة</button>{error&&<p className="text-xs text-rose-600">{error}</p>}</div><div className="max-h-40 overflow-auto text-xs">{employee.transactions?.map(x=><p key={x.id} className="border-b p-2">{x.occurredOn} — {x.type==='advance'?'سلفة':'راتب'}: {x.amount} {x.currency}</p>)}</div><button onClick={()=>window.print()} className="no-print flex w-full items-center justify-center gap-2 border p-3 text-xs font-black"><Printer className="h-4 w-4"/>طباعة أو حفظ PDF</button></div></Modal>};
const Modal=({title,close,children}:{title:string;close:()=>void;children:React.ReactNode})=><div className="fixed inset-0 z-[100] flex items-end justify-center bg-black/50 sm:items-center" onClick={close}><div className="w-full max-w-lg bg-white p-4 sm:rounded-sm" onClick={e=>e.stopPropagation()}><header className="mb-4 flex justify-between border-b pb-3"><b>{title}</b><button onClick={close}><X/></button></header>{children}</div></div>;
